name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../app_ui
  authentication_client:
    path: ../authentication_client/authentication_client
  blurhash: ^1.1.1
  database_client:
    path: ../database_client
  dio: ^5.7.0
  env:
    path: ../env
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  freeze: ^1.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  good_deeds_block:
    path: ../good_deeds_block
  http_parser: ^4.0.2
  image_picker_plus:
    path: ../image_picker_plus
  image_size_getter: ^2.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  ogp_data_extract: ^0.1.4
  powersync_repository:
    path: ../powersync_repository
  rxdart: ^0.28.0
  user_repository:
    path: ../user_repository
  uuid: ^4.5.1
  video_compress: ^3.1.3
  video_thumbnail: ^0.5.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
