// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzbUsr-U8sxPyaeIk7yCl_yuHUw8WahEU',
    appId: '1:92941533146:web:1d9ee0a33cc5ebfc4e4ae3',
    messagingSenderId: '92941533146',
    projectId: 'good-deeds-stg',
    authDomain: 'good-deeds-stg.firebaseapp.com',
    storageBucket: 'good-deeds-stg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqT5wVH4cey2b5ONyXVuElhEN2JCZA5Cs',
    appId: '1:92941533146:android:b049bbb1efbd85fc4e4ae3',
    messagingSenderId: '92941533146',
    projectId: 'good-deeds-stg',
    storageBucket: 'good-deeds-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUth3WSRh58GYPCxqQTlvJ3ZNUjBRUmI8',
    appId: '1:92941533146:ios:9986d032792b67ce4e4ae3',
    messagingSenderId: '92941533146',
    projectId: 'good-deeds-stg',
    storageBucket: 'good-deeds-stg.appspot.com',
    iosClientId: '92941533146-fs15l1u8r72pu6dt3s954ehli6mlg77f.apps.googleusercontent.com',
    iosBundleId: 'com.navi.goodDeedsApp.stg',
  );
}
