// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvPx8RiPLIdojv2BHyPG0FfcIG6HGzh4',
    appId: '1:192097266563:web:62b0993c8bbf08671ce4b6',
    messagingSenderId: '192097266563',
    projectId: 'good-deeds-prod',
    authDomain: 'good-deeds-prod.firebaseapp.com',
    storageBucket: 'good-deeds-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQwONs_vuzHJVEyoqPeCJdAfLEY_U9fi4',
    appId: '1:192097266563:android:2ac7fb92749a25781ce4b6',
    messagingSenderId: '192097266563',
    projectId: 'good-deeds-prod',
    storageBucket: 'good-deeds-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVJhfTNT6rco73tNX78qPZgd3oxmY524',
    appId: '1:192097266563:ios:d8aa584094667e541ce4b6',
    messagingSenderId: '192097266563',
    projectId: 'good-deeds-prod',
    storageBucket: 'good-deeds-prod.appspot.com',
    iosClientId: '192097266563-r6f2o1q017r26qjd9gdt6m31845ou59t.apps.googleusercontent.com',
    iosBundleId: 'com.navi.goodDeedsApp',
  );
}
